name = "aoc"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gladvent = ">= 2.2.1 and < 3.0.0"
nibble = ">= 1.1.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2024]
1 = { pt_1 = 1089, pt_2 = 6530 }
2 = { pt_1 = 19128774598, pt_2 = 21932258645 }
3 = { pt_1 = 17301, pt_2 = 172162399742349 }